export default {
    address: '[data-test="addressLine1Input-text"]',
    city: '[data-test="cityInput-text"]',
    checkoutShippingContinueButton: '#checkout-shipping-continue',
    country: '[data-test="countryCodeInput-select"]',
    creditcardNumber: '#ccNumber',
    customerAsGuestContinuebutton: '[data-test="customer-continue-as-guest-button"]',
    cvv:  '#ccCvv',
    emailBox: '[type=email]',
    expirationDate: '#ccExpiry',
    firstName: '[data-test="firstNameInput-text"]',
    lastName: '[data-test="lastNameInput-text"]',
    nameOnCard: '#ccName',
    phoneNumber: '[data-test="phoneInput-text"]',
    postalCode: '[data-test="postCodeInput-text"]',
    placeOrderButton:  '#checkout-payment-continue',
    privacyPolicyCheckbox: '#privacyPolicy',
}
